"""Add production queue fields to intent agent job

Revision ID: 1c9dd9e85cb4
Revises: 71d600df39f5
Create Date: 2026-08-30 15:28:09.445397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c9dd9e85cb4'
down_revision: Union[str, None] = '71d600df39f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Langgraph checkpoints ignored
    op.add_column('intent_agent_jobs', sa.Column('priority', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('intent_agent_jobs', sa.Column('sequence_number', sa.Integer(), autoincrement=True, nullable=False, server_default='0'))
    op.add_column('intent_agent_jobs', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.add_column('intent_agent_jobs', sa.Column('lease_until', sa.String(), nullable=True))
    op.add_column('intent_agent_jobs', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('intent_agent_jobs', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_intent_agent_jobs_idempotency_key'), 'intent_agent_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_intent_agent_jobs_sequence_number'), 'intent_agent_jobs', ['sequence_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_agent_jobs_sequence_number'), table_name='intent_agent_jobs')
    op.drop_index(op.f('ix_intent_agent_jobs_idempotency_key'), table_name='intent_agent_jobs')
    op.drop_column('intent_agent_jobs', 'idempotency_key')
    op.drop_column('intent_agent_jobs', 'worker_id')
    op.drop_column('intent_agent_jobs', 'lease_until')
    op.drop_column('intent_agent_jobs', 'max_attempts')
    op.drop_column('intent_agent_jobs', 'sequence_number')
    op.drop_column('intent_agent_jobs', 'priority')
    # Langgraph checkpoints ignored
    # ### end Alembic commands ###
