"""add agent_output to intent assessment

Revision ID: 291e8b8abcfb
Revises: 33d807814b39
Create Date: 2026-08-30 18:17:14.742300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '291e8b8abcfb'
down_revision: Union[str, None] = '33d807814b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intent_assessments', sa.Column('agent_output', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intent_assessments', 'agent_output')
    # ### end Alembic commands ###
