"""Remove sequence_number

Revision ID: 33d807814b39
Revises: 1c9dd9e85cb4
Create Date: 2026-08-30 15:33:54.199668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33d807814b39'
down_revision: Union[str, None] = '1c9dd9e85cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # langgraph ignored
    op.drop_index('ix_intent_agent_jobs_sequence_number', table_name='intent_agent_jobs')
    op.drop_column('intent_agent_jobs', 'sequence_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intent_agent_jobs', sa.Column('sequence_number', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_index('ix_intent_agent_jobs_sequence_number', 'intent_agent_jobs', ['sequence_number'], unique=False)
    # langgraph ignored
    # ### end Alembic commands ###
