"""Add Customer table

Revision ID: 6ffc64654162
Revises: 629a19ce1d0a
Create Date: 2026-08-29 09:51:37.001218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ffc64654162'
down_revision: Union[str, None] = '629a19ce1d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_telegram_chat_id'), 'customers', ['telegram_chat_id'], unique=False)

    # Insert mock customer for existing test sessions
    op.execute("INSERT INTO customers (id, name, phone, telegram_chat_id, created_at, updated_at) VALUES ('cust_demo', 'Demo User', '1234567890', NULL, NOW(), NOW()) ON CONFLICT DO NOTHING")

    op.drop_index('checkpoint_writes_thread_id_idx', table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_index('checkpoint_blobs_thread_id_idx', table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index('checkpoints_thread_id_idx', table_name='checkpoints')
    op.drop_table('checkpoints')
    op.create_foreign_key(None, 'customer_sessions', 'customers', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_sessions_user_id_fkey', 'customer_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_customers_telegram_chat_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
