"""Add intent intelligence fields

Revision ID: 71d600df39f5
Revises: 6af923d6bbf7
Create Date: 2026-08-30 10:30:19.520001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71d600df39f5'
down_revision: Union[str, None] = '6af923d6bbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intent_score_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=False),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_score_history_created_at'), 'intent_score_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_intent_score_history_id'), 'intent_score_history', ['id'], unique=False)
    op.create_index(op.f('ix_intent_score_history_session_id'), 'intent_score_history', ['session_id'], unique=False)
    op.add_column('customer_sessions', sa.Column('current_intent_score', sa.Float(), nullable=True))
    op.add_column('customer_sessions', sa.Column('intent_threshold', sa.Float(), nullable=True))
    op.add_column('customer_sessions', sa.Column('threshold_reached', sa.Boolean(), nullable=True))
    op.add_column('customer_sessions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('customer_sessions', sa.Column('finalized_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_sessions', 'finalized_at')
    op.drop_column('customer_sessions', 'status')
    op.drop_column('customer_sessions', 'threshold_reached')
    op.drop_column('customer_sessions', 'intent_threshold')
    op.drop_column('customer_sessions', 'current_intent_score')
    op.drop_index(op.f('ix_intent_score_history_session_id'), table_name='intent_score_history')
    op.drop_index(op.f('ix_intent_score_history_id'), table_name='intent_score_history')
    op.drop_index(op.f('ix_intent_score_history_created_at'), table_name='intent_score_history')
    op.drop_table('intent_score_history')
    # ### end Alembic commands ###
