"""add index to created_at

Revision ID: 73a40b926fa3
Revises: 6ffc64654162
Create Date: 2026-08-29 10:16:41.852902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a40b926fa3'
down_revision: Union[str, None] = '6ffc64654162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agent_executions_created_at'), 'agent_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_behavior_events_created_at'), 'behavior_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_commerce_actions_created_at'), 'commerce_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_created_at'), 'conversation_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_sessions_created_at'), 'customer_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_intent_assessments_created_at'), 'intent_assessments', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_assessments_created_at'), table_name='intent_assessments')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.drop_index(op.f('ix_customer_sessions_created_at'), table_name='customer_sessions')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversation_messages_created_at'), table_name='conversation_messages')
    op.drop_index(op.f('ix_commerce_actions_created_at'), table_name='commerce_actions')
    op.drop_index(op.f('ix_behavior_events_created_at'), table_name='behavior_events')
    op.drop_index(op.f('ix_agent_executions_created_at'), table_name='agent_executions')
    # ### end Alembic commands ###
